const gridMap = {

  terrain: ["oooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooo", 
            "oooooooooo  oooooooooooooooooo", 
            "xooooo   mmm  oooooooooooooooo",
            "xxo    mmm     mmooooooooooooo",
            "ooo   m  mmmmm  mooooooooooooo",
            "xxmmmmm       mmm oooooooooooo",
            "xx  m mm  m   m m  ooooooooooo",
            "xx    mmm m  m  mmmxxooooooooo",
            "xxm  m         m   xxxxoxooooo",
            "xxmmmm         mm   xooxxxoooo",
            "xxmmmm       mmmm   xxooxxoooo",
            "xxmm mm m  o mmmmm   xxxooxxxo",
            "xx m  mm m mmmm  mm  xxxooooxx",
            "xx  mmmmmmmmmm   mmmmxxxxxoooo",
            "xx  mmmmm  m    mmmmmxxxxxxooo",
            "xx    mmmm   mmm mmm xxxxxxxxo",
            "xx     mm mmmmmmmm mxxxxxxxxxo",
            "xx       mmmmmmm     xxxxxxxxx",
            "xx            m     m xxxxxxxx",
            "xx      m            mm xxxxxx",
            "xx                    mxxxxxxx",
            "xx                     xxxxxxx",
            "xx                     xxxxxxx",
            "xx                      xxxxxx",
            "xx                      xxxxxx",
            "xx                        xxxx",
            "xx                        xooo",
            "xx                      oooooo",
            "xx                     ooooooo",
            "xxxo                   ooooooo",
            "xxoo                  oooooooo",
            "xxoo                  oooooooo",
            "xooo                  oooooooo",
            "xxoo oooo              ooooooo",
            "xxo o  o             ooooooooo",
            "xxxxo                ooooooooo",
            "xxxooo              oooooooooo",
            "xxxxoooxo            ooooooooo",
            "xxxoxxxo      mm    oooooooooo",
            "xxxxxxxo     mm     oooooooooo",
            "xxxxxo     mm       oooooooooo",
            "xxxxxo   mm           oooooooo",
            "xxxxo            oo    ooooooo",
            "xxxx            ooooo   oooooo",
            "xx  m     oo  oooooooo  oooooo",
            "xx mm    ooooooooooooooooooooo",
            "  m   oooooooooooooooooooooooo",
            "    o oooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooo"],

  // segment IDs: 0 = southeastern line, 1 = southern, 2 = southwestern, 3 = northwestern, 4 = northern, 5 = northeastern

  riverSegments: [

    // Columbia
    {x: 4, y: 4, id: 1},
    {x: 5, y: 4, id: 2},
    {x: 5, y: 4, id: 1},
    {x: 6, y: 5, id: 2},
    {x: 6, y: 5, id: 1},
    {x: 6, y: 5, id: 0},
    {x: 7, y: 4, id: 1},
    {x: 7, y: 4, id: 0},
    {x: 7, y: 4, id: 5},
    {x: 7, y: 4, id: 4},
    {x: 7, y: 3, id: 2},
    {x: 7, y: 3, id: 3},
    {x: 7, y: 3, id: 4},
    {x: 8, y: 3, id: 3},
    {x: 8, y: 3, id: 4},
    {x: 9, y: 2, id: 3},

    // Snake
    {x: 8, y: 4, id: 1},
    {x: 9, y: 4, id: 2},
    {x: 9, y: 5, id: 4},
    {x: 9, y: 5, id: 5},
    {x: 9, y: 5, id: 0},
    {x: 9, y: 5, id: 1},
    {x: 9, y: 6, id: 3},
    {x: 9, y: 6, id: 2},
    {x: 9, y: 7, id: 3},
    {x: 9, y: 7, id: 2},
    {x: 9, y: 7, id: 1},
    {x: 10, y: 8, id: 2},
    {x: 10, y: 8, id: 1},
    {x: 11, y: 8, id: 2},
    {x: 11, y: 8, id: 1},
    {x: 12, y: 9, id: 2},
    {x: 12, y: 9, id: 1},
    {x: 12, y: 9, id: 0},
    {x: 12, y: 9, id: 5},
    {x: 13, y: 8, id: 3},
    {x: 13, y: 8, id: 4},
    
     ],

  getGridBackground: function(hexCoordinates) {
    switch(this.terrain[hexCoordinates.x][hexCoordinates.y]) {
      case "o": return { opacity: 1, color: 'deepskyblue' }; break;
      case "m": return { opacity: 1, color: 'sienna' }; break;
      case "x": return { opacity: 1, color: 'black' }; break;
      default:  return { opacity: 1, color: 'lightgreen' };
    } 
  }
}